# Generated by Django 4.2.30 on 2026-04-17 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, default='Tamil Nadu', max_length=100, null=True)),
                ('type', models.CharField(blank=True, choices=[('government', 'Government'), ('private', 'Private'), ('aided', 'Aided'), ('autonomous', 'Autonomous')], max_length=50, null=True)),
                ('affiliation', models.CharField(blank=True, choices=[('anna_university', 'Anna University'), ('anna_university_affiliated', 'Anna University Affiliated'), ('autonomous', 'Autonomous'), ('deemed_university', 'Deemed University')], max_length=100, null=True)),
                ('fees', models.IntegerField(blank=True, null=True)),
                ('scholarship_available', models.BooleanField(default=False)),
                ('placement_percentage', models.IntegerField(blank=True, null=True)),
                ('highest_package', models.IntegerField(blank=True, null=True)),
                ('average_package', models.IntegerField(blank=True, null=True)),
                ('top_recruiters', models.JSONField(blank=True, null=True)),
                ('naac_grade', models.CharField(blank=True, max_length=10, null=True)),
                ('nirf_ranking', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='colleges/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('website', models.URLField(blank=True, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('community', models.CharField(blank=True, choices=[('oc', 'OC'), ('bc', 'BC'), ('mbc', 'MBC'), ('sc', 'SC'), ('st', 'ST')], max_length=10, null=True)),
                ('cutoff_mark', models.IntegerField(blank=True, null=True)),
                ('preferred_district', models.CharField(blank=True, max_length=100, null=True)),
                ('preferred_stream', models.CharField(blank=True, max_length=50, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('admission', 'Admission'), ('placement', 'Placement'), ('event', 'Event'), ('holiday', 'Holiday'), ('exam', 'Exam'), ('announcement', 'Announcement')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='colleges.college')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='colleges.company')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('editor', 'Editor'), ('viewer', 'Viewer'), ('counselor', 'Counselor')], default='viewer', max_length=20)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stream', models.CharField(blank=True, choices=[('engineering', 'Engineering'), ('management', 'Management'), ('science', 'Science'), ('arts', 'Arts'), ('medical', 'Medical'), ('law', 'Law')], max_length=50, null=True)),
                ('duration_years', models.IntegerField(blank=True, null=True)),
                ('cutoff_oc', models.IntegerField(blank=True, null=True)),
                ('cutoff_bc', models.IntegerField(blank=True, null=True)),
                ('cutoff_mbc', models.IntegerField(blank=True, null=True)),
                ('cutoff_sc', models.IntegerField(blank=True, null=True)),
                ('cutoff_st', models.IntegerField(blank=True, null=True)),
                ('intake', models.IntegerField(blank=True, null=True)),
                ('fees', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='colleges.college')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
