# Generated by Django 6.0.4 on 2026-04-20 09:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('college_id', models.AutoField(primary_key=True, serialize=False)),
                ('college_name', models.CharField(max_length=200, unique=True)),
                ('short_name', models.CharField(blank=True, max_length=50, null=True)),
                ('counselling_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('logo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('location_city', models.CharField(max_length=100)),
                ('location_state', models.CharField(max_length=100)),
                ('location_pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('established_year', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('government', 'Government'), ('private', 'Private'), ('aided', 'Aided'), ('autonomous', 'Autonomous')], max_length=50, null=True)),
                ('affiliation', models.CharField(blank=True, choices=[('anna_university', 'Anna University'), ('anna_university_affiliated', 'Anna University Affiliated'), ('autonomous', 'Autonomous'), ('deemed_university', 'Deemed University')], max_length=100, null=True)),
                ('naac_grade', models.CharField(blank=True, max_length=5, null=True)),
                ('nirf_rank', models.IntegerField(blank=True, null=True)),
                ('website_url', models.URLField(blank=True, max_length=255, null=True)),
                ('email_domain', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('total_campus_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hostel_available', models.BooleanField(default=True)),
                ('placement_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('median_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('highest_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('avg_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['college_name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=150)),
                ('course_code', models.CharField(blank=True, max_length=20, null=True)),
                ('degree_type', models.CharField(choices=[('ug', 'UG'), ('pg', 'PG'), ('diploma', 'Diploma'), ('phd', 'PhD'), ('integrated', 'Integrated')], max_length=20)),
                ('degree_name', models.CharField(max_length=50)),
                ('duration_years', models.DecimalField(decimal_places=1, max_digits=3)),
                ('specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('intake_seats', models.IntegerField(blank=True, null=True)),
                ('cutoff_oc', models.DecimalField(blank=True, decimal_places=2, help_text='Cutoff mark for OC', max_digits=5, null=True)),
                ('cutoff_bc', models.DecimalField(blank=True, decimal_places=2, help_text='Cutoff mark for BC', max_digits=5, null=True)),
                ('cutoff_bcm', models.DecimalField(blank=True, decimal_places=2, help_text='Cutoff mark for BCM', max_digits=5, null=True)),
                ('cutoff_mbc', models.DecimalField(blank=True, decimal_places=2, help_text='Cutoff mark for MBC', max_digits=5, null=True)),
                ('cutoff_sc', models.DecimalField(blank=True, decimal_places=2, help_text='Cutoff mark for SC', max_digits=5, null=True)),
                ('cutoff_sca', models.DecimalField(blank=True, decimal_places=2, help_text='Cutoff mark for SCA', max_digits=5, null=True)),
                ('cutoff_st', models.DecimalField(blank=True, decimal_places=2, help_text='Cutoff mark for ST', max_digits=5, null=True)),
                ('scholarship_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Scholarship amount in INR per year', max_digits=12, null=True)),
                ('scholarship_criteria', models.TextField(blank=True, help_text='Eligibility criteria for scholarship', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='colleges.college')),
            ],
            options={
                'ordering': ['college__college_name', 'course_name'],
                'unique_together': {('college', 'course_code')},
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('editor', 'Editor'), ('viewer', 'Viewer'), ('counselor', 'Counselor')], default='viewer', max_length=20)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('admission', 'Admission'), ('exam', 'Exam'), ('result', 'Result'), ('event', 'Event'), ('holiday', 'Holiday'), ('placement', 'Placement'), ('workshop', 'Workshop'), ('seminar', 'Seminar'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='colleges.college')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\d{10}$')])),
                ('whatsapp_number', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(regex='^\\d{10}$')])),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(default='Tamil Nadu', max_length=100)),
                ('pincode', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(regex='^\\d{6}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('fee_id', models.AutoField(primary_key=True, serialize=False)),
                ('academic_year', models.CharField(max_length=9)),
                ('tuition_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('hostel_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mess_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transport_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('admission_fee_one_time', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_frequency', models.CharField(choices=[('yearly', 'Yearly'), ('semester', 'Semester'), ('quarterly', 'Quarterly')], default='yearly', max_length=20)),
                ('scholarship_available', models.BooleanField(default=False)),
                ('scholarship_details', models.TextField(blank=True, help_text='Criteria and amount', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='colleges.college')),
                ('course', models.ForeignKey(blank=True, help_text='NULL = common for all courses', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='colleges.course')),
            ],
            options={
                'verbose_name': 'Fee',
                'verbose_name_plural': 'Fees',
                'ordering': ['-academic_year', 'college__college_name'],
                'unique_together': {('college', 'course', 'academic_year')},
            },
        ),
    ]
