# Generated by Django 6.0.4 on 2026-04-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='fees',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
