# Generated by Django 6.0.4 on 2026-04-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0002_remove_course_specialization_remove_fees_tuition_fee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='tuition_fee',
            new_name='tuition_fee_management',
        ),
        migrations.AddField(
            model_name='course',
            name='tuition_fee_government',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Annual tuition fee for government quota', max_digits=12),
        ),
    ]
