# Generated by Django 6.0.4 on 2026-04-25 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0003_rename_tuition_fee_course_tuition_fee_management_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fees',
            unique_together={('college', 'academic_year')},
        ),
        migrations.RemoveField(
            model_name='fees',
            name='course',
        ),
    ]
