# Generated by Django 6.0.4 on 2026-04-25 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0004_alter_fees_unique_together_remove_fees_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fees',
            name='hostel_fees',
        ),
        migrations.AddField(
            model_name='fees',
            name='additional_fees',
            field=models.JSONField(blank=True, default=dict, help_text='Additional fees like: caution_deposit, alumni_fee, etc.'),
        ),
        migrations.AddField(
            model_name='fees',
            name='application_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Application fee for admission', max_digits=12),
        ),
        migrations.AddField(
            model_name='fees',
            name='book_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Book/library fee', max_digits=12),
        ),
        migrations.AddField(
            model_name='fees',
            name='exam_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Examination fee', max_digits=12),
        ),
        migrations.AddField(
            model_name='fees',
            name='lab_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Laboratory fee', max_digits=12),
        ),
        migrations.AddField(
            model_name='fees',
            name='miscellaneous_description',
            field=models.TextField(blank=True, help_text='Description of miscellaneous fees', null=True),
        ),
        migrations.AddField(
            model_name='fees',
            name='miscellaneous_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Other miscellaneous charges', max_digits=12),
        ),
        migrations.AddField(
            model_name='fees',
            name='sports_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sports facilities fee', max_digits=12),
        ),
        migrations.AlterField(
            model_name='fees',
            name='admission_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='One-time admission fee', max_digits=12),
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('hostel_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Hostel name (e.g., 'Boys Hostel - Block A', 'Ladies Hostel')", max_length=100)),
                ('gender', models.CharField(choices=[('boys', 'Boys'), ('girls', 'Girls'), ('both', 'Both')], default='boys', max_length=10)),
                ('room_type', models.IntegerField(choices=[(1, 'Normal Room + Common Bathroom'), (2, 'Normal Room + Attached Bathroom'), (3, 'AC Room + Common Bathroom'), (4, 'AC Room + Attached Bathroom')], help_text='Type of room')),
                ('fee_per_semester', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fee_per_year', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('caution_deposit', models.DecimalField(decimal_places=2, default=0, help_text='Refundable caution deposit', max_digits=12)),
                ('total_rooms', models.IntegerField(default=1, help_text='Total number of rooms of this type')),
                ('capacity_per_room', models.IntegerField(default=2, help_text='Number of students per room')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostels', to='colleges.college')),
            ],
            options={
                'verbose_name': 'Hostel',
                'verbose_name_plural': 'Hostels',
                'ordering': ['college__college_name', 'name', 'room_type'],
                'unique_together': {('college', 'name', 'room_type')},
            },
        ),
    ]
