# Generated by Django 6.0.4 on 2026-04-27 05:19

import colleges.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0005_remove_fees_hostel_fees_fees_additional_fees_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('course_id', models.IntegerField(blank=True, null=True)),
                ('quota_type', models.CharField(choices=[('management', 'Management Quota'), ('government', 'Government Quota')], default='management', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=10)),
                ('email_id', models.EmailField(max_length=254)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('nationality', models.CharField(default='Indian', max_length=50)),
                ('community', models.CharField(blank=True, choices=[('OC', 'OC'), ('BC', 'BC'), ('MBC', 'MBC'), ('SC', 'SC'), ('ST', 'ST')], max_length=10)),
                ('sub_caste', models.CharField(blank=True, max_length=50)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=20)),
                ('mother_tongue', models.CharField(blank=True, max_length=30)),
                ('aadhar_number', models.CharField(blank=True, max_length=14)),
                ('first_graduation', models.CharField(blank=True, max_length=255)),
                ('father_name', models.CharField(blank=True, max_length=100)),
                ('father_mobile', models.CharField(blank=True, max_length=10)),
                ('father_occupation', models.CharField(blank=True, max_length=100)),
                ('mother_name', models.CharField(blank=True, max_length=100)),
                ('mother_mobile', models.CharField(blank=True, max_length=10)),
                ('mother_occupation', models.CharField(blank=True, max_length=100)),
                ('family_annual_income', models.IntegerField(blank=True, null=True)),
                ('address_line1', models.TextField(blank=True)),
                ('address_line2', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=6)),
                ('tenth_school_name', models.CharField(blank=True, max_length=255)),
                ('tenth_board', models.CharField(blank=True, max_length=50)),
                ('tenth_year_of_passing', models.IntegerField(blank=True, null=True)),
                ('tenth_result_status', models.CharField(blank=True, choices=[('passed', 'Passed'), ('appearing', 'Appearing'), ('compartment', 'Compartment')], max_length=20)),
                ('tenth_marks_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('twelfth_school_name', models.CharField(blank=True, max_length=255)),
                ('twelfth_board', models.CharField(blank=True, max_length=50)),
                ('twelfth_year_of_passing', models.IntegerField(blank=True, null=True)),
                ('twelfth_result_status', models.CharField(blank=True, choices=[('passed', 'Passed'), ('appearing', 'Appearing'), ('compartment', 'Compartment')], max_length=20)),
                ('twelfth_marks_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('has_diploma', models.BooleanField(default=False)),
                ('diploma_college_name', models.CharField(blank=True, max_length=255)),
                ('diploma_board_university', models.CharField(blank=True, max_length=100)),
                ('diploma_year_of_passing', models.IntegerField(blank=True, null=True)),
                ('diploma_result_status', models.CharField(blank=True, choices=[('passed', 'Passed'), ('appearing', 'Appearing'), ('compartment', 'Compartment')], max_length=20)),
                ('diploma_marks_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('has_ug', models.BooleanField(default=False)),
                ('ug_college_name', models.CharField(blank=True, max_length=255)),
                ('ug_board_university', models.CharField(blank=True, max_length=100)),
                ('ug_year_of_passing', models.IntegerField(blank=True, null=True)),
                ('ug_result_status', models.CharField(blank=True, choices=[('passed', 'Passed'), ('appearing', 'Appearing'), ('compartment', 'Compartment')], max_length=20)),
                ('ug_marks_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=colleges.models.student_applications_directory_path)),
                ('aadhar_card', models.FileField(blank=True, null=True, upload_to=colleges.models.student_applications_directory_path)),
                ('tenth_marksheet', models.FileField(blank=True, null=True, upload_to=colleges.models.student_applications_directory_path)),
                ('twelfth_marksheet', models.FileField(blank=True, null=True, upload_to=colleges.models.student_applications_directory_path)),
                ('diploma_marksheet', models.FileField(blank=True, null=True, upload_to=colleges.models.student_applications_directory_path)),
                ('ug_marksheet', models.FileField(blank=True, null=True, upload_to=colleges.models.student_applications_directory_path)),
                ('community_marksheet', models.FileField(blank=True, null=True, upload_to=colleges.models.student_applications_directory_path)),
                ('declaration_accepted', models.BooleanField(default=False)),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='colleges.college')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Application',
                'verbose_name_plural': 'Student Applications',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
