# Generated by Django 6.0.4 on 2026-04-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0006_studentapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='pdf_copy',
            field=models.FileField(blank=True, null=True, upload_to='applications/pdfs/'),
        ),
    ]
