# Generated by Django 6.0.4 on 2026-04-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0007_studentapplication_pdf_copy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentapplication',
            name='course_id',
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='course_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='community',
            field=models.CharField(blank=True, choices=[('OC', 'OC'), ('BC', 'BC'), ('MBC', 'MBC'), ('SC', 'SC'), ('ST', 'ST'), ('SCA', 'SCA'), ('BCM', 'BCM'), ('DNC', 'DNC')], max_length=10),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='diploma_result_status',
            field=models.CharField(blank=True, choices=[('declared', 'Declared'), ('awaited', 'Awaited')], max_length=20),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='family_annual_income',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married')], max_length=20),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='tenth_result_status',
            field=models.CharField(blank=True, choices=[('declared', 'Declared'), ('awaited', 'Awaited')], max_length=20),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='twelfth_result_status',
            field=models.CharField(blank=True, choices=[('declared', 'Declared'), ('awaited', 'Awaited')], max_length=20),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='ug_result_status',
            field=models.CharField(blank=True, choices=[('declared', 'Declared'), ('awaited', 'Awaited')], max_length=20),
        ),
    ]
