# Generated by Django 6.0.4 on 2026-04-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0008_remove_studentapplication_course_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='courses_offered',
            field=models.JSONField(blank=True, default=list, help_text='List of course categories offered by the college'),
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('engineering', 'Engineering'), ('arts_science', 'Arts and Science'), ('polytechnic', 'Polytechnic'), ('allied_science', 'Allied Science'), ('medical', 'Medical'), ('law', 'Law'), ('nursing', 'Nursing'), ('management', 'Management'), ('pharmacy', 'Pharmacy'), ('education', 'Education')], default='engineering', help_text='Course category (e.g., Engineering, Medical, etc.)', max_length=50),
        ),
    ]
