# Generated by Django 6.0.4 on 2026-05-07 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0009_college_courses_offered_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='banner_image',
            field=models.URLField(blank=True, help_text='Banner image for college page', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='campus_images',
            field=models.JSONField(blank=True, default=list, help_text='Array of campus photos'),
        ),
        migrations.AddField(
            model_name='college',
            name='college_images',
            field=models.JSONField(blank=True, default=list, help_text='Array of image URLs for college campus, facilities, etc.'),
        ),
        migrations.AddField(
            model_name='college',
            name='cover_image',
            field=models.URLField(blank=True, help_text='Hero/cover image for college', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='facility_images',
            field=models.JSONField(blank=True, default=list, help_text='Array of facility/infrastructure photos'),
        ),
        migrations.AddField(
            model_name='college',
            name='hostel_images',
            field=models.JSONField(blank=True, default=list, help_text='Array of hostel photos'),
        ),
        migrations.AddField(
            model_name='college',
            name='lab_images',
            field=models.JSONField(blank=True, default=list, help_text='Array of laboratory photos'),
        ),
        migrations.AddField(
            model_name='college',
            name='library_images',
            field=models.JSONField(blank=True, default=list, help_text='Array of library photos'),
        ),
        migrations.AddField(
            model_name='college',
            name='sports_images',
            field=models.JSONField(blank=True, default=list, help_text='Array of sports facility photos'),
        ),
        migrations.AlterField(
            model_name='college',
            name='logo_url',
            field=models.URLField(blank=True, help_text='College logo URL', max_length=500, null=True),
        ),
    ]
