# Generated by Django 6.0.4 on 2026-06-03 13:50

import colleges.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0010_college_banner_image_college_campus_images_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hostel',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='college',
        ),
        migrations.RemoveField(
            model_name='studentapplication',
            name='college',
        ),
        migrations.RemoveField(
            model_name='studentapplication',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='user',
        ),
        migrations.RemoveField(
            model_name='timelineevent',
            name='college',
        ),
        migrations.RemoveField(
            model_name='college',
            name='affiliation',
        ),
        migrations.RemoveField(
            model_name='college',
            name='avg_salary',
        ),
        migrations.RemoveField(
            model_name='college',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='college',
            name='counselling_code',
        ),
        migrations.RemoveField(
            model_name='college',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='college',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='college',
            name='email_domain',
        ),
        migrations.RemoveField(
            model_name='college',
            name='established_year',
        ),
        migrations.RemoveField(
            model_name='college',
            name='facility_images',
        ),
        migrations.RemoveField(
            model_name='college',
            name='highest_salary',
        ),
        migrations.RemoveField(
            model_name='college',
            name='hostel_available',
        ),
        migrations.RemoveField(
            model_name='college',
            name='hostel_images',
        ),
        migrations.RemoveField(
            model_name='college',
            name='lab_images',
        ),
        migrations.RemoveField(
            model_name='college',
            name='library_images',
        ),
        migrations.RemoveField(
            model_name='college',
            name='logo_url',
        ),
        migrations.RemoveField(
            model_name='college',
            name='median_salary',
        ),
        migrations.RemoveField(
            model_name='college',
            name='naac_grade',
        ),
        migrations.RemoveField(
            model_name='college',
            name='nirf_rank',
        ),
        migrations.RemoveField(
            model_name='college',
            name='placement_percentage',
        ),
        migrations.RemoveField(
            model_name='college',
            name='sports_images',
        ),
        migrations.RemoveField(
            model_name='college',
            name='total_campus_area',
        ),
        migrations.RemoveField(
            model_name='college',
            name='type',
        ),
        migrations.RemoveField(
            model_name='college',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='college',
            name='website_url',
        ),
        migrations.RemoveField(
            model_name='course',
            name='cutoff_bc',
        ),
        migrations.RemoveField(
            model_name='course',
            name='cutoff_bcm',
        ),
        migrations.RemoveField(
            model_name='course',
            name='cutoff_mbc',
        ),
        migrations.RemoveField(
            model_name='course',
            name='cutoff_oc',
        ),
        migrations.RemoveField(
            model_name='course',
            name='cutoff_sc',
        ),
        migrations.RemoveField(
            model_name='course',
            name='cutoff_sca',
        ),
        migrations.RemoveField(
            model_name='course',
            name='cutoff_st',
        ),
        migrations.RemoveField(
            model_name='course',
            name='degree_name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='duration_years',
        ),
        migrations.RemoveField(
            model_name='course',
            name='intake_seats',
        ),
        migrations.RemoveField(
            model_name='course',
            name='scholarship_amount',
        ),
        migrations.RemoveField(
            model_name='course',
            name='scholarship_criteria',
        ),
        migrations.RemoveField(
            model_name='course',
            name='tuition_fee_government',
        ),
        migrations.RemoveField(
            model_name='course',
            name='tuition_fee_management',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='state',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(choices=[('AD', 'Artificial Intelligence and Data Science'), ('AE', 'Aeronautical Engineering'), ('AG', 'Agriculture Engineering'), ('AI', 'Agricultural and Irrigation Engineering (SS)'), ('AIML', 'Computer Science and Engineering (AI and Machine Learning)'), ('AS', 'Aerospace Engineering'), ('CS', 'Computer Science and Engineering'), ('EC', 'Electronics and Communication Engineering'), ('EE', 'Electrical and Electronics Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), ('IT', 'Information Technology')], help_text='Select course code', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='EnquiryForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('course_name', models.CharField(blank=True, max_length=255, null=True)),
                ('department_name', models.CharField(blank=True, max_length=255, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=10)),
                ('email_id', models.EmailField(max_length=254)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('community', models.CharField(blank=True, choices=[('OC', 'OC'), ('BC', 'BC'), ('MBC', 'MBC'), ('SC', 'SC'), ('ST', 'ST'), ('SCA', 'SCA'), ('BCM', 'BCM'), ('DNC', 'DNC')], max_length=10)),
                ('aadhar_number', models.CharField(blank=True, max_length=14)),
                ('father_name', models.CharField(blank=True, max_length=100)),
                ('father_mobile', models.CharField(blank=True, max_length=10)),
                ('mother_name', models.CharField(blank=True, max_length=100)),
                ('mother_mobile', models.CharField(blank=True, max_length=10)),
                ('address_line1', models.TextField(blank=True)),
                ('address_line2', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=6)),
                ('tenth_marks_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('twelfth_marks_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('has_diploma', models.BooleanField(default=False)),
                ('diploma_marks_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('has_ug', models.BooleanField(default=False)),
                ('ug_marks_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=colleges.models.student_applications_directory_path)),
                ('aadhar_card', models.FileField(blank=True, null=True, upload_to=colleges.models.student_applications_directory_path)),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='colleges.college')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Application',
                'verbose_name_plural': 'Student Applications',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.DeleteModel(
            name='Fees',
        ),
        migrations.DeleteModel(
            name='Hostel',
        ),
        migrations.DeleteModel(
            name='StudentApplication',
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
        migrations.DeleteModel(
            name='TimelineEvent',
        ),
    ]
