# Generated by Django 6.0.4 on 2026-06-09 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0011_alter_hostel_unique_together_remove_hostel_college_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['college__college_name', 'category', 'course_name']},
        ),
        migrations.AddField(
            model_name='enquiryform',
            name='reference_name',
            field=models.CharField(blank=True, help_text='Name of the person who referred the student', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='enquiryform',
            name='selected_category',
            field=models.CharField(blank=True, choices=[('engineering', 'Engineering and Technology'), ('arts_science', 'Arts and Science'), ('polytechnic', 'Polytechnic'), ('allied_health_science', 'Allied Health Science'), ('medical', 'Medical'), ('law', 'Law'), ('nursing', 'Nursing'), ('management', 'Management'), ('computer_applications', 'Computer Applications'), ('pharmacy', 'Pharmacy'), ('agriculture', 'Agricultural Science'), ('physiotherapy', 'Physiotherapy'), ('occupational_therapy', 'Occupational Therapy'), ('architecture', 'Architecture'), ('education', 'Education'), ('physical_education', 'Physical Education')], help_text='Selected course category', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='enquiryform',
            name='selected_course',
            field=models.ForeignKey(blank=True, help_text='The selected course from the Course model', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='colleges.course'),
        ),
        migrations.AddField(
            model_name='enquiryform',
            name='selected_degree_type',
            field=models.CharField(blank=True, choices=[('ug', 'UG'), ('pg', 'PG'), ('diploma', 'Diploma'), ('phd', 'PhD'), ('integrated', 'Integrated')], help_text='Selected degree type', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='campus_images',
            field=models.JSONField(blank=True, default=list, help_text='Array of campus photos. Format: ["https://example.com/campus1.jpg"]'),
        ),
        migrations.AlterField(
            model_name='college',
            name='college_images',
            field=models.JSONField(blank=True, default=list, help_text='Array of image URLs for college campus, facilities, etc. Format: ["https://example.com/image1.jpg"]'),
        ),
        migrations.AlterField(
            model_name='college',
            name='courses_offered',
            field=models.JSONField(blank=True, default=list, help_text='List of course categories offered by the college. Format: ["engineering", "pharmacy", "law"]'),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('engineering', 'Engineering and Technology'), ('arts_science', 'Arts and Science'), ('polytechnic', 'Polytechnic'), ('allied_health_science', 'Allied Health Science'), ('medical', 'Medical'), ('law', 'Law'), ('nursing', 'Nursing'), ('management', 'Management'), ('computer_applications', 'Computer Applications'), ('pharmacy', 'Pharmacy'), ('agriculture', 'Agricultural Science'), ('physiotherapy', 'Physiotherapy'), ('occupational_therapy', 'Occupational Therapy'), ('architecture', 'Architecture'), ('education', 'Education'), ('physical_education', 'Physical Education')], default='engineering', help_text='Course category (e.g., Engineering, Medical, etc.)', max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(choices=[('AD', 'Artificial Intelligence and Data Science'), ('CS', 'Computer Science and Engineering'), ('CS_CYBER', 'Computer Science and Engineering (Cyber Security)'), ('IT', 'Information Technology'), ('AIML', 'Artificial Intelligence and Machine Learning'), ('EC', 'Electronics and Communication Engineering'), ('CS_IOT', 'Computer Science Engineering with IOT'), ('BT', 'Bio Technology'), ('BME', 'Biomedical Engineering'), ('EEE', 'Electrical and Electronics Engineering'), ('ME', 'Mechanical Engineering'), ('AE', 'Aeronautical Engineering'), ('CE', 'Civil Engineering'), ('FT', 'Food Technology'), ('AG', 'Agriculture Engineering'), ('ROBO_AI', 'Robotics and Artificial Intelligence'), ('MECHATRONICS', 'Mechatronics Engineering'), ('ENV', 'Environmental Science and Technology'), ('ECE', 'Electrical and Computer Engineering'), ('BCOM', 'B.Com'), ('BCOM_CA', 'B.Com - Computer Applications'), ('BCOM_PA', 'B.Com - Professional Accounting'), ('BCA', 'B.C.A'), ('BSC_CS', 'B.Sc - Computer Science'), ('BSC_AI_DS', 'B.Sc - Artificial Intelligence & Data Science'), ('BSC_IT', 'B.Sc - Information Technology'), ('BSC_CYBER', 'B.Sc - Cyber Security & Ethical Hacking'), ('BBA', 'B.B.A'), ('BBA_LOGISTICS', 'B.B.A - Logistic & Supply Chain Management'), ('BSC_DATA_SCIENCE', 'B.Sc - Data Science & Analytics'), ('BSC_IOT', 'B.Sc Internet of Things (IoT)'), ('BSC_DEFENCE', 'B.Sc - Defence and Strategic Studies'), ('BSC_VISUAL_COMM', 'B.Sc - Visual Communication'), ('BSC_FORENSIC', 'B.Sc - Forensic Science'), ('BBA_AVIATION', 'B.B.A - Aviation Management'), ('BA_ENGLISH', 'B.A English'), ('BA_PUBLIC_ADMIN', 'B.A Public Administration'), ('BA_SOCIAL_WORK', 'B.A Social Work'), ('BSC_HOTEL_MGT', 'B.Sc - Hotel Management & Catering Science'), ('MA_ENGLISH', 'M.A English'), ('MSC_CS', 'M.Sc Computer Science'), ('MSC_IT', 'M.Sc Information Technology'), ('MCOM', 'M.Com'), ('MCOM_CA', 'M.Com (CA)'), ('MSC_BIOCHEM', 'MSc Biochemistry'), ('MSC_BIO_TECH', 'M.Sc Biotechnology'), ('MSC_MATHS', 'M.Sc Mathematics'), ('MSC_MICRO', 'M.Sc Microbiology'), ('MSC_PHYSICS', 'M.Sc Physics'), ('MSC_CHEMISTRY', 'M.Sc Chemistry'), ('BSC_AECT', 'B.Sc - Accident and Emergency Care Technology'), ('BSC_CPPT', 'B.Sc - Cardio Pulmonary and Perfusion Technology'), ('BSC_CVT', 'B.Sc - Cardio Vascular Technology'), ('BSC_CCT', 'B.Sc - Critical Care Technology'), ('BSC_DT', 'B.Sc - Dialysis Technology'), ('BSC_MLT', 'B.Sc - Medical Laboratory Technology'), ('BSC_OTAT', 'B.Sc - Operation Theatre and Anaesthesia Technology'), ('BOPTOM', 'B.Optometry'), ('BSC_PA', 'B.Sc - Physician Assistant'), ('BSC_RIT', 'B.Sc - Radiography and Imaging Technology'), ('MSC_AT', 'M.Sc - Anaesthesia Tech'), ('MSC_DT', 'M.Sc - Dialysis Technology'), ('MSC_MM', 'M.Sc - Medical Microbiology'), ('MSC_MB', 'M.Sc - Medical Biochemistry'), ('MSC_RIT', 'M.Sc - Radiography and Imaging Tech'), ('MSC_AECT', 'M.Sc - Accident and Emergency Care'), ('BPHARM', 'B.Pharm - Bachelor of Pharmacy'), ('DPHARM', 'D.Pharm - Diploma in Pharmacy'), ('MPHARM_PHARM', 'M.Pharm - Pharmaceuticals'), ('MPHARM_ANALYSIS', 'M.Pharm - Pharmaceutical Analysis'), ('MPHARM_PCOG', 'M.Pharm - Pharmacognosy'), ('PHARMD', 'Pharm.D'), ('BSC_NURSING', 'B.Sc - Nursing'), ('GNM', 'GNM - General Nursing and Midwifery'), ('PB_BSC_NURSING', 'Post Basic B.Sc - Nursing'), ('MSC_NURSING', 'M.Sc - Nursing'), ('BPT', 'B.P.T - Bachelor of Physiotherapy'), ('MPT_ORTHO', 'M.P.T - Orthopaedics'), ('MPT_NEURO', 'M.P.T - Neurology'), ('MPT_SPORTS', 'M.P.T - Sports & Fitness'), ('BOT', 'B.O.T - Bachelor of Occupational Therapy'), ('BSC_AGRI_HONS', 'B.Sc (Hons) Agriculture'), ('BSC_HORT_HONS', 'B.Sc (Hons) Horticulture'), ('BARCH', 'B.Arch - Bachelor of Architecture'), ('BDES_INTERIOR', 'B.Des - Interior Design'), ('BA_LLB', 'B.A. LLB (Hons.)'), ('BBA_LLB', 'B.B.A. LLB (Hons.)'), ('MBA', 'M.B.A - Master of Business Administration'), ('MCA', 'M.C.A - Master of Computer Applications'), ('DIP_CE', 'Diploma in Computer Engineering'), ('DIP_EEE', 'Diploma in Electrical & Electronics Engineering'), ('DIP_ME', 'Diploma in Mechanical Engineering'), ('BED', 'B.Ed - Bachelor of Education'), ('MED', 'M.Ed - Master of Education'), ('BPED', 'B.P.Ed - Bachelor of Physical Education'), ('BPES', 'B.P.E.S - Bachelor of Physical Education and Sports')], help_text='Select course', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(help_text='Course name', max_length=200),
        ),
        migrations.AlterField(
            model_name='enquiryform',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
