# Generated by Django 6.0.4 on 2026-06-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0012_alter_course_options_enquiryform_reference_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiryform',
            name='reference_name',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(choices=[('AD', 'Artificial Intelligence and Data Science'), ('CS', 'Computer Science and Engineering'), ('CS_CYBER', 'Computer Science and Engineering (Cyber Security)'), ('IT', 'Information Technology'), ('AIML', 'Artificial Intelligence and Machine Learning'), ('EC', 'Electronics and Communication Engineering'), ('CS_IOT', 'Computer Science Engineering with IOT'), ('BT', 'Bio Technology'), ('BME', 'Biomedical Engineering'), ('EEE', 'Electrical and Electronics Engineering'), ('ME', 'Mechanical Engineering'), ('AE', 'Aeronautical Engineering'), ('CE', 'Civil Engineering'), ('FT', 'Food Technology'), ('AG', 'Agriculture Engineering'), ('ROBO_AI', 'Robotics and Artificial Intelligence'), ('MECHATRONICS', 'Mechatronics Engineering'), ('ENV', 'Environmental Science and Technology'), ('ECE', 'Electrical and Computer Engineering'), ('MCA', 'Master of Computer Applications'), ('MBA', 'Master of Business Administration'), ('ME_CADCAM', 'M.E - CAD/CAM'), ('ME_CSE', 'M.E - Computer Science and Engineering'), ('ME_CS', 'M.E - Communication Systems'), ('ME_PED', 'M.E - Power Electronics and Drives'), ('BCOM', 'B.Com'), ('BCOM_CA', 'B.Com - Computer Applications'), ('BCOM_PA', 'B.Com - Professional Accounting'), ('BCA', 'B.C.A'), ('BSC_CS', 'B.Sc - Computer Science'), ('BSC_AI_DS', 'B.Sc - Artificial Intelligence & Data Science'), ('BSC_IT', 'B.Sc - Information Technology'), ('BSC_CYBER', 'B.Sc - Cyber Security & Ethical Hacking'), ('BBA', 'B.B.A'), ('BBA_LOGISTICS', 'B.B.A - Logistic & Supply Chain Management'), ('BSC_DATA_SCIENCE', 'B.Sc - Data Science & Analytics'), ('BSC_IOT', 'B.Sc Internet of Things (IoT)'), ('BSC_DEFENCE', 'B.Sc - Defence and Strategic Studies'), ('BSC_VISUAL_COMM', 'B.Sc - Visual Communication'), ('BSC_FORENSIC', 'B.Sc - Forensic Science'), ('BBA_AVIATION', 'B.B.A - Aviation Management'), ('BA_ENGLISH', 'B.A English'), ('BA_PUBLIC_ADMIN', 'B.A Public Administration'), ('BA_SOCIAL_WORK', 'B.A Social Work'), ('BSC_HOTEL_MGT', 'B.Sc - Hotel Management & Catering Science'), ('BSC_AIML', 'B.Sc - Artificial Intelligence and Machine Learning'), ('BSC_BC', 'B.Sc - Biochemistry'), ('BSC_BT', 'B.Sc - Biotechnology'), ('BSC_MB', 'B.Sc - Microbiology'), ('BSC_MATHS', 'B.Sc - Mathematics'), ('BSC_FTCD', 'B.Sc - Fashion Technology and Costume Designing'), ('MA_TAMIL', 'M.A Tamil'), ('MA_ENGLISH', 'M.A English'), ('MSC_CS', 'M.Sc Computer Science'), ('MSC_IT', 'M.Sc Information Technology'), ('MCOM', 'M.Com'), ('MCOM_CA', 'M.Com (CA)'), ('MCA', 'M.C.A'), ('MSC_BIOCHEM', 'MSc Biochemistry'), ('MSC_BIO_TECH', 'M.Sc Biotechnology'), ('MSC_MATHS', 'M.Sc Mathematics'), ('MSC_MICRO', 'M.Sc Microbiology'), ('MSC_PHYSICS', 'M.Sc Physics'), ('MSC_CHEMISTRY', 'M.Sc Chemistry'), ('BSC_AECT', 'B.Sc - Accident and Emergency Care Technology'), ('BSC_CPPT', 'B.Sc - Cardio Pulmonary and Perfusion Technology'), ('BSC_CVT', 'B.Sc - Cardio Vascular Technology'), ('BSC_CCT', 'B.Sc - Critical Care Technology'), ('BSC_DT', 'B.Sc - Dialysis Technology'), ('BSC_MLT', 'B.Sc - Medical Laboratory Technology'), ('BSC_OTAT', 'B.Sc - Operation Theatre and Anaesthesia Technology'), ('BSC_APBH', 'B.Sc - Applied Psychology and Behavioural Health'), ('BSC_CND', 'B.Sc - Nutrition and Dietetics'), ('BSC_NEP', 'B.Sc - Neuro Electro Physiology'), ('BOPTOM', 'B.Optometry'), ('BSC_PA', 'B.Sc - Physician Assistant'), ('BSC_RIT', 'B.Sc - Radiography and Imaging Technology'), ('MSC_AT', 'M.Sc - Anaesthesia Tech'), ('MSC_DT', 'M.Sc - Dialysis Technology'), ('MSC_MM', 'M.Sc - Medical Microbiology'), ('MSC_MB', 'M.Sc - Medical Biochemistry'), ('MSC_RIT', 'M.Sc - Radiography and Imaging Tech'), ('MSC_AECT', 'M.Sc - Accident and Emergency Care'), ('BPHARM', 'B.Pharm - Bachelor of Pharmacy'), ('DPHARM', 'D.Pharm - Diploma in Pharmacy'), ('MPHARM_PHARM', 'M.Pharm - Pharmaceuticals'), ('MPHARM_ANALYSIS', 'M.Pharm - Pharmaceutical Analysis'), ('MPHARM_PCOG', 'M.Pharm - Pharmacognosy'), ('PHARMD', 'Pharm.D'), ('BSC_NURSING', 'B.Sc - Nursing'), ('GNM', 'GNM - General Nursing and Midwifery'), ('PB_BSC_NURSING', 'Post Basic B.Sc - Nursing'), ('MSC_NURSING', 'M.Sc - Nursing'), ('BPT', 'B.P.T - Bachelor of Physiotherapy'), ('MPT_MUSCULOSKELETAL', 'M.P.T - Musculoskeletal Science'), ('MPT_ORTHO', 'M.P.T - Orthopaedics'), ('MPT_NEURO', 'M.P.T - Neurology'), ('MPT_SPORTS', 'M.P.T - Sports & Fitness'), ('BOT', 'B.O.T - Bachelor of Occupational Therapy'), ('BSC_AGRI_HONS', 'B.Sc (Hons) Agriculture'), ('BSC_HORT_HONS', 'B.Sc (Hons) Horticulture'), ('BARCH', 'B.Arch - Bachelor of Architecture'), ('BDES_INTERIOR', 'B.Des - Interior Design'), ('BA_LLB', 'B.A. LLB (Hons.)'), ('BBA_LLB', 'B.B.A. LLB (Hons.)'), ('BCOM_LLB', 'B.Com. LLB (Hons.)'), ('MBA', 'M.B.A - Master of Business Administration'), ('MCA', 'M.C.A - Master of Computer Applications'), ('DIP_CE', 'Diploma in Computer Engineering'), ('DIP_EEE', 'Diploma in Electrical & Electronics Engineering'), ('DIP_ME', 'Diploma in Mechanical Engineering'), ('BED', 'B.Ed - Bachelor of Education'), ('MED', 'M.Ed - Master of Education'), ('BPED', 'B.P.Ed - Bachelor of Physical Education'), ('BPES', 'B.P.E.S - Bachelor of Physical Education and Sports')], help_text='Select course', max_length=100),
        ),
        migrations.AlterField(
            model_name='enquiryform',
            name='diploma_marks_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='enquiryform',
            name='ug_marks_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
