colleges_list = [
"A K T Memorial College of Engineering and Technology",
"A R College of Engineering and Technology",
"A R Engineering College",
"A R J College of Engineering and Technology",
"A V C College of Engineering",
"A V S Engineering College",
"AAA College of Engineering and Technology",
"Aalim Muhammed Salegh Academy of Architecture",
"Aalim Muhammed Salegh College of Engineering",
"Adhi College of Engineering and Technology",
"Adhiparasakthi College of Engineering",
"Adhiparasakthi Engineering College",
"Adhiyamaan College of Engineering (Autonomous)",
"Adithya Institute of Technology",
"Agni College of Technology",
"Aishwarya College of Engineering and Technology",
"Akshaya College of Engineering and Technology",
"Alagappa Chettiar Government College of Engineering and Technology (Autonomous)",
"Al-Ameen Engineering College (Autonomous)",
"Alpha College of Engineering",
"AMRITA College of Engineering and Technology",
"Anand Institute of Higher Technology",
"Anand School of Architecture",
"Angel College of Engineering and Technology",
"Anjalai Ammal-Mahalingam Engineering College",
"Anna University Regional Campus - Coimbatore",
"Anna University Regional Campus - Madurai",
"Anna University Regional Campus - Tirunelveli",
"Annai College of Engineering and Technology",
"Annai Mathammal Sheela Enginereing College",
"Annai Mira College of Engineering and Technology",
"Annai Terasa College of Engineering",
"Annai Vailankanni College of Engineering",
"Annai Veilankannis College of Engineering",
"Annamalai University Faculty of Engineering and Technology",
"Annamalaiar College of Engineering",
"Annapoorana Engineering College",
"Apollo Engineering College",
"Arasu Engineering College",
"Arifa Institute of Technology(Formerly Haji sheik Ismail)",
"Ariyalur Engineering College",
"Arjun College of Technology",
"Arulmigu Meenakshi Amman College of Engineering",
"Arulmurugan College of Engineering",
"Arunachala College of Engineering for Women",
"Arunai Engineering College",
"Asan Memorial College of Engineering and Technology",
"Asian College of Engineering and Technology",
"As-Salam College of Engineering and Technology",
"AVS College of Technology",        
"Bannari Amman Institute of Technology (Autonomous)",
"Bethlahem Institute of Engineering",
"Bharath Niketan Engineering College",
"Bharathidasan Engineering College",
"Bharathiyar Institute of Engineering for Women",
"Builders engineering college",
"C Abdul Hakeem College of Engineering and Technology",
"C K College of Engineering and Technology",
"C M S College of Engineering and Technology",
"C M S College of Engineering",
"C S I College of Engineering",
"C S I Institute of Technology",
"C.A.R.E School of Architecture",
"CAAD - Chennai Academy of Architecture and Design",
"CAPE Institute of Technology",
"CARE College of Engineering",
"Central Electrochemical Research Institute CECRI)",
"Central Institute of Plastics Engineering and Technology (CIPET)",
"Chendu College of Engineering & Technology",
"CHENDURAN COLLEGE OF ENGINEERING & TECHNOLOGY",
"Chennai Institute of Technology",
"Cheran College of Engineering",
"Chettinad College of Engineering and Technology",
"Christ the King Engineering College",
"Christian College of Engineering and Technology",
"Coimbatore Institute of Engineering and Technolgoy (Autonomous)",
"Coimbatore Institute of Technology (Autonomous)",
"D M I College of Engineering",
"D M I Engineering College",
"Davinci School of Design and Architecture",
"Dhaanish Ahmed College of Engineering",
"Dhaanish Ahmed Institute of Technology",
"Dhanalakshmi College of Engineering",
"Dhanalakshmi Srinivasan College of Engineering and Technology",
"Dhanalakshmi Srinivasan College of Engineering",
"Dhanalakshmi Srinivasan Engineering College (Autonomous)",
"Dhirajlal Gandhi College of Technology",
"Dr. G U Pope College of Engineering",
"Dr. Mahalingam College of Engineering and Technology",
"Dr. N G P Institute of Technology",
"Dr. Nagarathinams College of Engineering",
"Dr. Navalar Nedunchezhian College of Engineering",
"Dr. Sivanthi Aditanar College of Engineering",
"E G S Pillay Engineering College (Autonomous)",
"EASA College of Engineering and Technology",
"Easwari Engineering College (Autonomous)",
"Einstein College of Engineering",
"Er. Perumal Manimekalai College of Engineering",
"Erode Sengunthar Engineering College (Autonomous)",
"Excel Engineering College (Autonomous)",
"Fatima Michael College of Engineering & Technology",
"Francis Xavier Engineering College (Autonomous)",
"G K M College of Engineering and Technology",
"Ganadipathy Tulsi’s Jain Engineering College",
"Ganapathy Chettiar College of Engineering and Technology",
"Ganesh College of Engineering",
"Global Institute of Engineering and Technology",
"Gnanamani College of Technology",
"Gojan School of Business and Technology",
"GOOD SHEPHERD COLLEGE OF ENGINEERING AND TECHNOLOGY",
"Government College of Engineering (Autonomous)",
"Government College of Engineering (Autonomous)",
"Government College of Engineering",
"Government College of Engineering",
"Government College of Engineering",
"Government College of Engineering",
"Government College of Engineering",
"Government College of Technology (Autonomous)",
"Grace College of Engineering",
"GRT Institute of Engineering and Technology",
"Hindustan Institute of Technology (Autonomous)",
"Hindusthan College of Engineering and Technology",
"Hindusthan School of Architecture",
"Holy Cross Engineering College",
"I F E T College of Engineering (Autonomous)",
"Idhaya Engineering College for Women",
"Immanuel Arasar J J College of Engineering",
"Indian Institute of Handloom Technology",
"Indira Institute of Engineering and Technology",
"Indra Ganesan College of Engineering",
"Infant Jesus College of Engineering",
"INFO Institute of Engineering",
"Government Engineering College",
"International Maritime Academy",
"J C T College of Engineering and Technology",
"J J College of Engineering and Technology",
"J K K Muniraja College of Technology",
"J K K Nataraja College of Engineering and Technology",
"J N N Institute of Engineering",
"J P College of Engineering",
"J.K. College of Architecture",
"Jagannath Institute of Technology",
"Jai Shriram Engineering College",
"Jainee College of Engineering and Technology",
"Jairupaa College of Engineering",
"Jansons Institute of Technology",
"Jawahar Engineering College",
"Jawahar School of Architecture Planning and Design",
"Jaya College of Engineering and Technology",
"Jaya Engineering College",
"Jaya Institute of Technology",
"Jaya Sakthi Engineering College",
"Jaya School of Architecture",
"Jayalakshmi Institute of Technology",
"Jayam College of Engineering and Technology",
"Jayamatha Engineering College",
"Jayaraj Annapackiam CSI College of Engineering",
"Jayaram College of Engineering and Technology",
"JEI Mathaajee College of Engineering",
"Jeppiaar Institute of Technology",
"Jeppiar Engineering College",
"Jerusalem College of Engineering (Autonomous)",
"K C G College of Technology",
"K L N College of Engineering (Autonomous)",
"K P R Institute of Engineering and Technology (Autonomous)",
"K Ramakrishnan College of Engineering (Autonomous)",
"K Ramakrishnan College of Technology (Autonomous)",
"K S K College of Engineering and Technology",
"K S R College of Engineering (Autonomous)",
"K S R Institute for Engineering and Technology",
"K S Rangasamy College of Technology (Autonomous)",
"Kamaraj College of Engineering and Technology (Autonomous)",
"Karaikudi Institute of Technology",
"Karpagam College of Engineering (Autonomous)",
"Karpagam Institute of Technology",
"Karpagavinayaga College of Engineering and Technology",
"Kathir College of Engineering",
"KGISL Institute of Technology",
"Kings College of Engineering",
"Kings Engineering College",
"Kingston Engineering College",
"KIT-Kalaignar Karunanidhi Institute of Technology (Autonomous)",
"Knowledge Institute of Technology",
"Kongu Engineering College (Autonomous)",
"Kongu School of Architecture",
"Kongunadu College of Engineering and Technology",  
"Krishnaswamy Collge of Engineering and Technology",   
"Kumaraguru College of Technology (Autonomous)",
"Kurinji College of Engineering and Technology",
"Latha Mathavan Engineering College",
"Lord Jegannath College of Engineering and Technology",
"Lord Venkateshwara Engineering College",
"Lourdes Mount College of Engineering and Technology",
"Loyola Institute of Technology and Science",
"Loyola Institute of Technology",
"Loyola-ICAM College of Engineering and Technology",
"M E T Engineering College",
"M I E T Engineering College",
"M Kumarasamy College of Engineering (Autonomous)",
"M P Nachimuthu M Jagannathan Engineering College",
"M R K Institute of Technology",
"M.A.M. College of Engineering and Technology",
"M.A.M. College of Engineering",
"M.A.M. School of Architecture",
"M.A.M. School of Engineering",
"Madha Engineering College",
"Madha Institute of Engineering and Technology",
"Madha school of Architecture",
"Madurai Institute of Engineering & Technology",
"Maha Bharathi Engineering College",
"Mahakavi Bharathiyar College of Engineering and Technology",
"Mahath Amma Institute of Engineering and Technology (MIET)",
"Mahendra College of Engineering",
"Mahendra Engineering College (Autonomous)",
"Mahendra Engineering College for Women",
"Mahendra Institute of Engineering and Technology",
"Mahendra Institute of Technology (Autonomous)",
"Mailam Engineering College",
"Mangayarkarasi College of Engineering",
"MAR Ephraem College of Engineering & Technology",
"MARG Instiute of Design & Architecture Swarnabhoomi (MIDAS)",
"Maria College of Engineering and Technology",
"Marthandam College of Engineering & Technology",
"McGans Ooty School Of Architecture",
"Measi Academy of Architecture",
"Meenakshi College of Engineering",
"Meenakshi Ramaswamy Engineering College",
"Meenakshi Sundararajan Engineering College",
"Mepco Schlenk Engineering College (Autonomous)",
"Misrimal Navajee Munoth Jain Engineering College",
"Misrimal Navajee Munoth Jain School of Architecture",
"MMES ACADEMY OF ARCHITECTURE",
"Mohamed Sathak A J Academy of Architecture",
"Mohamed Sathak A J College of Engineering",
"Mohamed Sathak Engineering College",
"Mookambigai College of Engineering",
"Mother Terasa College of Engineering and Technology",
"Mount Zion College of Engineering and Technology",
"Muthayammal College of Engineering",
"Muthayammal Engineering College (Autonomous)",
"N P R College of Engineering and Technology",
"N S N College of Engineering and Technology",
"Nadar Saraswathi College of Engineering and Technology",
"Nandha College of Technology",
"Nandha Engineering College (Autonomous)",
"Narasus Sarathy Institute of Technology",
"Narayanaguru College of Engineering",
"National Engineering College (Autonomous)",
"Nehru Institute of Engineering and Technology",
"Nehru Institute of Technology",
"Nehru School of Architecture",
"Nellai College of Engineering",
"Nelliandavar Institute of Technology",
"New Prince Shri Bhavani College of Engineering and Technology",
"OASYS Institute of Technology",
"Oxford College of Engineering",
"Oxford Engineering College",
"P A College of Engineering and Technology (Autonomous)",
"P B College of Engineering",
"P G P College of Engineering and Technology",
"P M R Engineering College",
"P P G Institute of Technology",
"P R Engineering College",
"P S N A Colllege of Engineering and Technology",
"P S N College of Engineering and Technology (Autonomous)",
"P S N Engineering College",
"P S N Institute of Technology & Science",
"P S R Engineering College (Autonomous)",
"P S V College of Engineeering and Technology",
"P T Lee Chengalvaraya Naicker College of Engineering and",
"P T R College of Engineering and Technology",
"P.S.R.R College of Engineering  Appayanaickenpatti",
"Paavai College of Engineering",
"Paavai College of Technology",
"Paavai Engineering College (Autonomous)",
"Pallavan College of Engineering",
"Pandian Saraswathi Yadav Engineering College",
"Panimalar Engineering College",
"Panimalar Institute of Technology",
"Papni School of Architecture",
"Parisutham Institute of Technology and Science",
"Park College of Engineering and Technology",
"Park College of Technology",
"Park Institute of Architecture",
"Pavendhar Bharathidasan College of Engineering and",
"PERI Institute of Technology",
"PET Engineering College",
"Podhigai College of Engineering and Technology",
"Pollachi Institute of Engineering and Technology",
"Ponjesly College of Engineering",
"Prathyusha Engineering college",
"Prime College of Architecture and Planning",
"Prime Nest College of Architecture and Planning",
"Prince Dr. K Vasudevan College of Engineering and Technology",
"Prince Shri Venkateshwara Padmavathy Enginering College",
"Priyadarshini Engineering College",
"PSG College of Technology (Autonomous)",
"PSG Institute of Technology and Applied Research",
"R M D Engineering College",
"R M K College of Engineering and Technology",
"R M K Engineering College (Autonomous)",
"R V S College of Engineering and Technology",
"R V S College of Engineering",
"R V S Educational Trust’s Groups of Institutions (Integrated Campus)",
"R V S Padmavathy School of Architecture",
"R V S School of Architecture",
"R V S Technical Campus-Coimbatore",
"Rajalakshmi Engineering College (Autonomous)",
"Rajalakshmi Institute of Technology",
"Rajalakshmi School of Architecture",
"Rajas Institute of Technology",
"Rajiv Gandhi College of Engineering",
"Ramco Institute of Technology",
"Ranganathan Architecture College",
"Ranippettai Engineering College",
"Rathinam School of Architecture",
"Rathinam Technical Campus",
"Renganayagi Varatharaj College of Engineering",
"Roever Engineering College",
"Rohini College of Engineering & Technology",
"Rrase College of Engineering",
"S A Engineering College (Autonomous)",
"S K P Engineering College",
"S N S College of Engineering (Autonomous)",
"S N S College of Technology (Autonomous)",
"S S M College of Engineering",
"S Veerasamy Chettiar College of Engineering and Technology"
"SACS-M A V M M Engineering College",
"Salem College of Engineering and Technology",
"SAMS College of Engineering and Technology",
"San Academy of Architecture",
"Saranathan College of Engineering",
"Saraswathy College of Engineering and Technology",
"Sardar Raja College of Engineering",
"Sasi Creative School of Archiecture",
"Sasurie College of Engineering",
"Satyam College of Engineering & Technology",
"Saveetha Engineering College (Autonomous)",
"SBM College of Engineering and Technology",
"SCAD College of Engineering and Technology",
"School Of Architecture Coimbatore Institute Of Engineering And",
"Selvam College of Technology",
"Sembodai Rukmani Varatharajan Engineering College",
"Sengunthar College of Engineering",
"Sengunthar Engineering College (Autonomous)",
"Sethu Institute of Technology (Autonomous)",
"Shanmuganathan Engineering College",
"Shivani Engineering College"
"Shree Motilal Kanhaiyalal (SMK)Fomra Institute of Technology",
"Shree Sathyam College of Engineering and Technology",
"Shree Venkateshwara Hi-Tech Engineering College",
"Shreenivasa Engineering College",
"Shri Angalamman College of Engineering and Technology",
"Sigma College of Architecture",
"Sir Issac Newton College of Engineering and Technology",
"Sivaji College of Engineering and Technology",
"SMR East Coast College of Engineering & Technology",
"SOLAMALAI COLLEGE OF ENGINEERIG",
"Sona College of Technology (Autonomous)",
"Sree Krishna College of Engineering",
"Sree Raaja Raajan College of Engineering & Technology",
"Sree Sakthi Engineering College",
"Sree Sastha Institute of Engineering and Technology",
"Sree Sowdambiga College of Engineering",
"SRG Engineering College",
"Sri Balaji Chockalingam Engineering College",
"Sri Bharathi Engineering College for Women",
"Sri Eshwar College of Engineering (Autonomous)",
"Sri Jayaram Institute of Engineering and Technology",
"Sri Krishna College of Engineering",
"Sri Krishna College of Engineering and Technology (Autonomous)",
"Sri Krishna College of Technology (Autonomous)",
"Sri Krishna Engineering College",
"Sri Krishna Institute of Technology",
"Sri Muthukumaran Institute of Technology",
"Sri Ram Engineering College",
"Sri Ramakrishna College of Engineering",
"Sri Ramakrishna Engineering College (Autonomous)",
"Sri Ramakrishna Institute of Technology (Autonomous)",
"Sri Ramanujar Engineering College",
"Sri Ranganathar Institute of Engineering and Technology",
"Sri Rangapoopathi College of Engineering",
"Sri Sai Ram Institute of Technology (Autonomous)",
"Sri Sai Ranganathan Engineering College",
"Sri Sairam Engineering College (Autonomous)",
"Sri Shakthi Institute of Engineering and Technology",
"Sri Shanmugha College of Engineering and Technology",
"Sri Sivasubramaniya Nadar College of Engineering (Autonomous)",
"Sri Subramanya College of Engineering and Technology",
"Sri Venkateswara College of Engineering (Autonomous)",
"Sri Venkateswara College of Engineering and Technology",
"Sri Venkateswaraa College of Technology",
"Sri Vidhya College of Engineering and Technology",
"SRM TRP Engineering College",
"SRM Valliammai Engineering College (Autonomous)",
"SSM Institute of Engineering and Technology",
"St. Annes College of Engineering and Technology",
"St. Joseph College of Engineering",
"St. Joseph’s College of Engineering",
"St. Joseph’s Institute of Technology",
"St. Josephs College of Engineering and Technology",
"St. Michael College of Engineering and Technology",
"St. Mother Theresa Engineering College",
"St. Peters College of Engineering and Technology",
"St. Xavier Catholic College of Engineering",
"Star Lion College of Engineering & Technology",
"Stella Marys College of Engineering",
"Study World College of Engineering",
"Sudharsan Engineering College",
"Suguna College of Engineering",
"Surya College of Engineering",
"Surya Engineering College",
"Surya Group of Institutions",
"Surya School of Architecture",
"Syed Ammal Engineering College",
"T J S Engineering College",
"T S M Jain College of Technology",
"T.J INSTITUTE OF TECHNOLOGY",
"Tagore Engineering College",
"Tagore Institute of Engineering and Technology",
"Tamilnadu College of Engineering",
"Tamilnadu School of Architecture",
"Thamirabharani Engineering College",
"Thangavelu Engineering College",
"Thanthai Periyar Government Institute of Technology",
"The Kavery Engineering College",
"Theni Kammavar Sangam College of Technology",
"Thiagarajar College of Engineering (Autonomous)",
"Thirumalai Engineering College",
"Thiruvalluvar College of Engineering and Technology",
"Trichy Engineering College",
"Udaya School of Engineering",
"Ultra College of Engineering and Technology",
"United Institute of Technology",
"Universal College of Engineering and Technology",
"University College of Engineering",
"University College of Engineering",
"University College of Engineering",
"University College of Engineering",
"University College of Engineering",
"University College of Engineering",
"University College of Engineering",
"University College of Engineering",
"University College of Engineering",
"University College of Engineering",
"University College of Engineering",
"University College of Engineering",
"University College of Engineering",
"University College of Engineering",
"University College of Engineering",
"University College of Engineering",
"University Departments of Anna University",
"University Departments of Anna University",
"University Departments of Anna University",
"University Departments of Anna University",
"University V.O.C. College of Engineering",
"Unnamalai Institute of Technology",
"V P Muthaiah Pillai Meenakshi Ammal Engineering College for Women"
"V R S College of Engineering and Technology"
"V S A Group of Institutions"
"V S B College of Engineering Technical Campus"
"V S B Engineering College"
"V V College of Engineering"
"V.P.M.M. College of Architecture for Women"
"Vaigai College of Engineering"
"Vandayar Engineering College"
"Varuvan Vadivelan Institute of Technology"
"Vel Tech High Tech Dr. Rangarajan Dr. Sakunthala Engineering College"
"Vel Tech Multi Tech Dr. Rangarajan Dr. Sakunthala Engineering College (Autonomous)"
"Velalar College of Engineering and Technology (Autonomous)"
"Velammal College of Engineering and Technology"
"Velammal Engineering College (Autonomous)"
"Velammal Institute of Technology"
"Vetri Vinayaha College of Engineering and Technology"
"Vi Institute of Technology"
"Vidhya Vikkas College of Engineering and Technology"
"Vins Christian College of Engineering"
"Vins Christian Womens College of Engineering"
"Vivekanandha College of Engineering for Women (Autonomous)"
"Vivekanandha College of Technology for Women"
"Excel College Of Architecture And Planning"
"Tips School of Architecture"

]